bunch of updates :)
amcharts/amcharts3-react pull request #30
Opened 2017-02-13 10:48 UTC by RahavLussato

1. change componentDidUpdate to componentWillReceiveProps : detection of changes need to happen before the chart will update to avoid multiple updates because the same changes. its more correct way by the best practices of react.

2. add new prop `chartVersion`: in my case i have situations that i making math calc on all the data and change all the data, in this cases i don't want to waste time to go all over the data, i want to clear all the and make a new chart (its much faster).

3.add new prop `activeSkip`: in most of the cases when chart is get new data provider that bigger then the old one, the old data is not changed and i want to handle only the new indexes (again performance issue) so i added activeSkip prop to enable this, and new part that check if the new `dataProvider` is bigger than the old one and activeSkip is turned on it will handle only the part of the data that exists in the new `dataProvider`

2017-03-07 13:08 UTC, iddan commented
Why isn't it merged? Is it tested?

2017-03-07 13:11 UTC, RahavLussato commented
the comment is not valid anymore, i changed more stuff from the time i wrote that.

2017-03-07 13:12 UTC, RahavLussato commented
its hard to contribute when its take long time to merge PR

2017-04-03 09:05 UTC, Pauan commented
@RahavLussato I'm very sorry for the delay on this. I'll review this pull request now.

2017-04-04 13:14 UTC, Pauan requested changes
Thank you for your work, but here are some things we need to address before I will merge this.

Also, please do not commit the `node_modules` folder into git.

2017-04-04 13:14 UTC, Pauan commented on amcharts3-react.js
> +          if (!isEqual(x,y)) {
The type checks above means that the `default` case will only handle simple types like strings.

Therefore, using `isEqual` is unnecessary and inefficient.

2017-04-04 13:14 UTC, Pauan commented on amcharts3-react.js
> +    return {didUpdateData:didUpdateData, didUpdateClass:didUpdateClass};
See the comment below for `validateData`

2017-04-04 13:14 UTC, Pauan commented on package.json
> +    "lodash": "^4.17.4"
I'd rather not have a dependency on `lodash`, especially because it's not needed (see comments above).

2017-04-04 13:14 UTC, Pauan commented on package.json
> +  "version": "1.1.9",
I prefer to put multiple changes into a single update, so I prefer to bump the version number when releasing, not when making the changes.

2017-04-04 13:14 UTC, Pauan commented on amcharts3-react.js
> +const isEqual = require('lodash/isEqual');
This is not needed, see comments below.

2020-03-24 08:15 UTC, closed without merging